//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYP
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Photo
    {
        public int id { get; set; }
        public int id_main_page { get; set; }
        public string photo { get; set; }
    
        public virtual Main_Page Main_Page { get; set; }
    }
}
