//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MYPEntities : DbContext
    {
        public MYPEntities()
            : base("name=MYPEntities")
        {
        }

        private static MYPEntities _context = new MYPEntities();

        public static MYPEntities GetContext()
        {
            if (_context == null)
                _context = new MYPEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact_Page> Contact_Page { get; set; }
        public virtual DbSet<Flat> Flat { get; set; }
        public virtual DbSet<List_Photo> List_Photo { get; set; }
        public virtual DbSet<Main_Page> Main_Page { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Privatization_Page> Privatization_Page { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
