//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int id_operation { get; set; }
        public int id_status { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public Nullable<int> id_flat { get; set; }
        public System.DateTime date { get; set; }
        public string telephone
        {
            get
            {
                return "+7 " + phone.Substring(1, 3) + " " + phone.Substring(4, 3) + "-" + phone.Substring(7, 2) + "-" + phone.Substring(9, 2);
            }
        }


        public string status_button
        {
            get
            {
                if (Status.id == 1)
                    return "Принять в обработку";
                else if (Status.id == 2)
                    return "Выполнить";
                else
                    return "Отменить";
            }
        }
        public virtual Flat Flat { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual Status Status { get; set; }
    }
}
